# Generated by Django 3.2.5 on 2021-07-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0002_alter_baseuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='user_type',
        ),
    ]
